# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 869)
        MainWindow.setStyleSheet("QWidget#mainwidget {\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainwidget = QtWidgets.QWidget(self.centralwidget)
        self.mainwidget.setObjectName("mainwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.mainwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.left_panel = QtWidgets.QWidget(self.splitter)
        self.left_panel.setMinimumSize(QtCore.QSize(260, 0))
        self.left_panel.setMaximumSize(QtCore.QSize(360, 16777215))
        self.left_panel.setStyleSheet("QWidget#left_panel { border: 1px solid #d0d7de; border-radius: 0px; }")
        self.left_panel.setObjectName("left_panel")
        self.leftPanelLayout = QtWidgets.QVBoxLayout(self.left_panel)
        self.leftPanelLayout.setContentsMargins(9, 9, 9, 0)
        self.leftPanelLayout.setSpacing(8)
        self.leftPanelLayout.setObjectName("leftPanelLayout")
        self.groupBoxFileInfo = QtWidgets.QGroupBox(self.left_panel)
        self.groupBoxFileInfo.setObjectName("groupBoxFileInfo")
        self.formFileInfo = QtWidgets.QFormLayout(self.groupBoxFileInfo)
        self.formFileInfo.setObjectName("formFileInfo")
        self.labelFile = QtWidgets.QLabel(self.groupBoxFileInfo)
        self.labelFile.setObjectName("labelFile")
        self.formFileInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelFile)
        self.lbl_filename = QtWidgets.QLineEdit(self.groupBoxFileInfo)
        self.lbl_filename.setStyleSheet("QLineEdit { border: none; background: transparent; padding: 0px; }")
        self.lbl_filename.setReadOnly(True)
        self.lbl_filename.setObjectName("lbl_filename")
        self.formFileInfo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_filename)
        self.labelProject = QtWidgets.QLabel(self.groupBoxFileInfo)
        self.labelProject.setObjectName("labelProject")
        self.formFileInfo.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelProject)
        self.lbl_project = QtWidgets.QLabel(self.groupBoxFileInfo)
        self.lbl_project.setObjectName("lbl_project")
        self.formFileInfo.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_project)
        self.labelJob = QtWidgets.QLabel(self.groupBoxFileInfo)
        self.labelJob.setObjectName("labelJob")
        self.formFileInfo.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelJob)
        self.lbl_job = QtWidgets.QLabel(self.groupBoxFileInfo)
        self.lbl_job.setObjectName("lbl_job")
        self.formFileInfo.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_job)
        self.labelTime = QtWidgets.QLabel(self.groupBoxFileInfo)
        self.labelTime.setObjectName("labelTime")
        self.formFileInfo.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelTime)
        self.lbl_time = QtWidgets.QLabel(self.groupBoxFileInfo)
        self.lbl_time.setObjectName("lbl_time")
        self.formFileInfo.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_time)
        self.leftPanelLayout.addWidget(self.groupBoxFileInfo)
        self.groupBoxVisualization = QtWidgets.QGroupBox(self.left_panel)
        self.groupBoxVisualization.setObjectName("groupBoxVisualization")
        self.formVisualization = QtWidgets.QFormLayout(self.groupBoxVisualization)
        self.formVisualization.setObjectName("formVisualization")
        self.labelPointSize = QtWidgets.QLabel(self.groupBoxVisualization)
        self.labelPointSize.setObjectName("labelPointSize")
        self.formVisualization.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPointSize)
        self.spin_point_size = QtWidgets.QSpinBox(self.groupBoxVisualization)
        self.spin_point_size.setMinimum(1)
        self.spin_point_size.setMaximum(10)
        self.spin_point_size.setProperty("value", 1)
        self.spin_point_size.setObjectName("spin_point_size")
        self.formVisualization.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_point_size)
        self.cmb_colormap = QtWidgets.QComboBox(self.groupBoxVisualization)
        self.cmb_colormap.setVisible(False)
        self.cmb_colormap.setObjectName("cmb_colormap")
        self.cmb_colormap.addItem("")
        self.cmb_colormap.addItem("")
        self.cmb_colormap.addItem("")
        self.cmb_colormap.addItem("")
        self.cmb_colormap.addItem("")
        self.formVisualization.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_colormap)
        self.leftPanelLayout.addWidget(self.groupBoxVisualization)
        self.groupBoxSettings = QtWidgets.QGroupBox(self.left_panel)
        self.groupBoxSettings.setObjectName("groupBoxSettings")
        self.formSettings = QtWidgets.QFormLayout(self.groupBoxSettings)
        self.formSettings.setObjectName("formSettings")
        self.labelThicknessField = QtWidgets.QLabel(self.groupBoxSettings)
        self.labelThicknessField.setObjectName("labelThicknessField")
        self.formSettings.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelThicknessField)
        self.cmb_dist_field = QtWidgets.QComboBox(self.groupBoxSettings)
        self.cmb_dist_field.setObjectName("cmb_dist_field")
        self.cmb_dist_field.addItem("")
        self.formSettings.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_dist_field)
        self.labelMinTarget = QtWidgets.QLabel(self.groupBoxSettings)
        self.labelMinTarget.setObjectName("labelMinTarget")
        self.formSettings.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelMinTarget)
        self.spin_target_min = QtWidgets.QDoubleSpinBox(self.groupBoxSettings)
        self.spin_target_min.setMaximum(9999.0)
        self.spin_target_min.setProperty("value", 50.0)
        self.spin_target_min.setObjectName("spin_target_min")
        self.formSettings.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_target_min)
        self.labelMaxTarget = QtWidgets.QLabel(self.groupBoxSettings)
        self.labelMaxTarget.setObjectName("labelMaxTarget")
        self.formSettings.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelMaxTarget)
        self.spin_target_max = QtWidgets.QDoubleSpinBox(self.groupBoxSettings)
        self.spin_target_max.setMaximum(9999.0)
        self.spin_target_max.setProperty("value", 150.0)
        self.spin_target_max.setObjectName("spin_target_max")
        self.formSettings.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_target_max)
        self.leftPanelLayout.addWidget(self.groupBoxSettings)
        self.groupBoxResults = QtWidgets.QGroupBox(self.left_panel)
        self.groupBoxResults.setObjectName("groupBoxResults")
        self.formResults = QtWidgets.QFormLayout(self.groupBoxResults)
        self.formResults.setObjectName("formResults")
        self.labelArea = QtWidgets.QLabel(self.groupBoxResults)
        self.labelArea.setObjectName("labelArea")
        self.formResults.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelArea)
        self.lbl_area = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_area.setObjectName("lbl_area")
        self.formResults.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_area)
        self.labelTargetCoverage = QtWidgets.QLabel(self.groupBoxResults)
        self.labelTargetCoverage.setObjectName("labelTargetCoverage")
        self.formResults.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTargetCoverage)
        self.lbl_target_coverage = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_target_coverage.setObjectName("lbl_target_coverage")
        self.formResults.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_target_coverage)
        self.labelVolume = QtWidgets.QLabel(self.groupBoxResults)
        self.labelVolume.setObjectName("labelVolume")
        self.formResults.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelVolume)
        self.lbl_volume = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_volume.setObjectName("lbl_volume")
        self.formResults.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_volume)
        self.labelMeanThickness = QtWidgets.QLabel(self.groupBoxResults)
        self.labelMeanThickness.setObjectName("labelMeanThickness")
        self.formResults.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelMeanThickness)
        self.lbl_mean_thickness = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_mean_thickness.setObjectName("lbl_mean_thickness")
        self.formResults.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_mean_thickness)
        self.labelMinThickness = QtWidgets.QLabel(self.groupBoxResults)
        self.labelMinThickness.setObjectName("labelMinThickness")
        self.formResults.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelMinThickness)
        self.lbl_min_thickness = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_min_thickness.setObjectName("lbl_min_thickness")
        self.formResults.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_min_thickness)
        self.labelMaxThickness = QtWidgets.QLabel(self.groupBoxResults)
        self.labelMaxThickness.setObjectName("labelMaxThickness")
        self.formResults.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelMaxThickness)
        self.lbl_max_thickness = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_max_thickness.setObjectName("lbl_max_thickness")
        self.formResults.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_max_thickness)
        self.labelStdThickness = QtWidgets.QLabel(self.groupBoxResults)
        self.labelStdThickness.setObjectName("labelStdThickness")
        self.formResults.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelStdThickness)
        self.lbl_std_thickness = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_std_thickness.setObjectName("lbl_std_thickness")
        self.formResults.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lbl_std_thickness)
        self.labelNumPoints = QtWidgets.QLabel(self.groupBoxResults)
        self.labelNumPoints.setObjectName("labelNumPoints")
        self.formResults.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelNumPoints)
        self.lbl_num_points = QtWidgets.QLabel(self.groupBoxResults)
        self.lbl_num_points.setObjectName("lbl_num_points")
        self.formResults.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lbl_num_points)
        self.leftPanelLayout.addWidget(self.groupBoxResults)
        self.groupBoxDistribution = QtWidgets.QGroupBox(self.left_panel)
        self.groupBoxDistribution.setObjectName("groupBoxDistribution")
        self.vboxDistribution = QtWidgets.QVBoxLayout(self.groupBoxDistribution)
        self.vboxDistribution.setObjectName("vboxDistribution")
        self.labelBelow = QtWidgets.QLabel(self.groupBoxDistribution)
        self.labelBelow.setObjectName("labelBelow")
        self.vboxDistribution.addWidget(self.labelBelow)
        self.lbl_below = QtWidgets.QLabel(self.groupBoxDistribution)
        self.lbl_below.setStyleSheet("color:#c53030;font-weight:bold;")
        self.lbl_below.setObjectName("lbl_below")
        self.vboxDistribution.addWidget(self.lbl_below)
        self.labelWithin = QtWidgets.QLabel(self.groupBoxDistribution)
        self.labelWithin.setObjectName("labelWithin")
        self.vboxDistribution.addWidget(self.labelWithin)
        self.lbl_within = QtWidgets.QLabel(self.groupBoxDistribution)
        self.lbl_within.setStyleSheet("color:#276749;font-weight:bold;")
        self.lbl_within.setObjectName("lbl_within")
        self.vboxDistribution.addWidget(self.lbl_within)
        self.labelAbove = QtWidgets.QLabel(self.groupBoxDistribution)
        self.labelAbove.setObjectName("labelAbove")
        self.vboxDistribution.addWidget(self.labelAbove)
        self.lbl_above = QtWidgets.QLabel(self.groupBoxDistribution)
        self.lbl_above.setStyleSheet("color:#315aff;font-weight:bold;")
        self.lbl_above.setObjectName("lbl_above")
        self.vboxDistribution.addWidget(self.lbl_above)
        self.leftPanelLayout.addWidget(self.groupBoxDistribution)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.leftPanelLayout.addItem(spacerItem)
        self.segment_panel = QtWidgets.QWidget(self.splitter)
        self.segment_panel.setMinimumSize(QtCore.QSize(260, 0))
        self.segment_panel.setMaximumSize(QtCore.QSize(360, 16777215))
        self.segment_panel.setStyleSheet("QWidget#segment_panel { border: 1px solid #d0d7de; border-radius: 0px; }")
        self.segment_panel.setObjectName("segment_panel")
        self.segmentPanelLayout = QtWidgets.QVBoxLayout(self.segment_panel)
        self.segmentPanelLayout.setContentsMargins(9, 9, 9, 0)
        self.segmentPanelLayout.setSpacing(8)
        self.segmentPanelLayout.setObjectName("segmentPanelLayout")
        self.groupBoxCreateSegment = QtWidgets.QGroupBox(self.segment_panel)
        self.groupBoxCreateSegment.setObjectName("groupBoxCreateSegment")
        self.vboxCreateSegment = QtWidgets.QVBoxLayout(self.groupBoxCreateSegment)
        self.vboxCreateSegment.setObjectName("vboxCreateSegment")
        self.hboxRange = QtWidgets.QHBoxLayout()
        self.hboxRange.setObjectName("hboxRange")
        self.labelFrom = QtWidgets.QLabel(self.groupBoxCreateSegment)
        self.labelFrom.setObjectName("labelFrom")
        self.hboxRange.addWidget(self.labelFrom)
        self.spin_sel_min = QtWidgets.QDoubleSpinBox(self.groupBoxCreateSegment)
        self.spin_sel_min.setMinimum(-9999.0)
        self.spin_sel_min.setMaximum(99999.0)
        self.spin_sel_min.setProperty("value", 75.0)
        self.spin_sel_min.setObjectName("spin_sel_min")
        self.hboxRange.addWidget(self.spin_sel_min)
        self.labelTo = QtWidgets.QLabel(self.groupBoxCreateSegment)
        self.labelTo.setObjectName("labelTo")
        self.hboxRange.addWidget(self.labelTo)
        self.spin_sel_max = QtWidgets.QDoubleSpinBox(self.groupBoxCreateSegment)
        self.spin_sel_max.setMinimum(-9999.0)
        self.spin_sel_max.setMaximum(99999.0)
        self.spin_sel_max.setProperty("value", 100.0)
        self.spin_sel_max.setObjectName("spin_sel_max")
        self.hboxRange.addWidget(self.spin_sel_max)
        self.vboxCreateSegment.addLayout(self.hboxRange)
        self.btn_select_range = QtWidgets.QPushButton(self.groupBoxCreateSegment)
        self.btn_select_range.setObjectName("btn_select_range")
        self.vboxCreateSegment.addWidget(self.btn_select_range)
        self.btn_polygon = QtWidgets.QPushButton(self.groupBoxCreateSegment)
        self.btn_polygon.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_polygon.setCheckable(True)
        self.btn_polygon.setObjectName("btn_polygon")
        self.vboxCreateSegment.addWidget(self.btn_polygon)
        self.btn_clear_sel = QtWidgets.QPushButton(self.groupBoxCreateSegment)
        self.btn_clear_sel.setObjectName("btn_clear_sel")
        self.vboxCreateSegment.addWidget(self.btn_clear_sel)
        self.segmentPanelLayout.addWidget(self.groupBoxCreateSegment)
        self.groupBox = QtWidgets.QGroupBox(self.segment_panel)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_sel_count = QtWidgets.QLabel(self.groupBox)
        self.lbl_sel_count.setStyleSheet("color:#2c5282; font-weight:bold; font-size:10px;")
        self.lbl_sel_count.setObjectName("lbl_sel_count")
        self.verticalLayout.addWidget(self.lbl_sel_count)
        self.btn_add_seg = QtWidgets.QPushButton(self.groupBox)
        self.btn_add_seg.setObjectName("btn_add_seg")
        self.verticalLayout.addWidget(self.btn_add_seg)
        self.segmentPanelLayout.addWidget(self.groupBox)
        self.layer_box = QtWidgets.QGroupBox(self.segment_panel)
        self.layer_box.setStyleSheet("QGroupBox { margin-top: 10px; }")
        self.layer_box.setObjectName("layer_box")
        self.vboxLayerManager = QtWidgets.QVBoxLayout(self.layer_box)
        self.vboxLayerManager.setObjectName("vboxLayerManager")
        self.hint = QtWidgets.QLabel(self.layer_box)
        self.hint.setStyleSheet("color:#718096; font-size:9px;")
        self.hint.setObjectName("hint")
        self.vboxLayerManager.addWidget(self.hint)
        self.list_layers = QtWidgets.QListWidget(self.layer_box)
        self.list_layers.setMinimumSize(QtCore.QSize(0, 18))
        self.list_layers.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_layers.setObjectName("list_layers")
        self.vboxLayerManager.addWidget(self.list_layers)
        self.lbl_current_layer = QtWidgets.QLabel(self.layer_box)
        self.lbl_current_layer.setStyleSheet("color:#2c5282; font-weight:bold; font-size:14px;")
        self.lbl_current_layer.setText("")
        self.lbl_current_layer.setObjectName("lbl_current_layer")
        self.vboxLayerManager.addWidget(self.lbl_current_layer)
        self.segmentPanelLayout.addWidget(self.layer_box)
        self.action_box = QtWidgets.QGroupBox(self.segment_panel)
        self.action_box.setObjectName("action_box")
        self.vboxActions = QtWidgets.QVBoxLayout(self.action_box)
        self.vboxActions.setObjectName("vboxActions")
        self.note = QtWidgets.QLabel(self.action_box)
        self.note.setStyleSheet("color:#718096; font-size:9px;")
        self.note.setWordWrap(True)
        self.note.setObjectName("note")
        self.vboxActions.addWidget(self.note)
        self.btn_calculate = QtWidgets.QPushButton(self.action_box)
        self.btn_calculate.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_calculate.setObjectName("btn_calculate")
        self.vboxActions.addWidget(self.btn_calculate)
        self.btn_export_pdf = QtWidgets.QPushButton(self.action_box)
        self.btn_export_pdf.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_export_pdf.setObjectName("btn_export_pdf")
        self.vboxActions.addWidget(self.btn_export_pdf)
        self.progress_bar = QtWidgets.QProgressBar(self.action_box)
        self.progress_bar.setVisible(False)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.vboxActions.addWidget(self.progress_bar)
        self.segmentPanelLayout.addWidget(self.action_box)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.segmentPanelLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.splitter)
        self.horizontalLayout_2.addWidget(self.mainwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.toolBarMain = QtWidgets.QToolBar(MainWindow)
        self.toolBarMain.setIconSize(QtCore.QSize(24, 24))
        self.toolBarMain.setObjectName("toolBarMain")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarMain)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExportPdf = QtWidgets.QAction(MainWindow)
        self.actionExportPdf.setObjectName("actionExportPdf")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTopView = QtWidgets.QAction(MainWindow)
        self.actionTopView.setObjectName("actionTopView")
        self.actionBottomView = QtWidgets.QAction(MainWindow)
        self.actionBottomView.setObjectName("actionBottomView")
        self.actionFrontView = QtWidgets.QAction(MainWindow)
        self.actionFrontView.setObjectName("actionFrontView")
        self.actionBackView = QtWidgets.QAction(MainWindow)
        self.actionBackView.setObjectName("actionBackView")
        self.actionRightView = QtWidgets.QAction(MainWindow)
        self.actionRightView.setObjectName("actionRightView")
        self.actionLeftView = QtWidgets.QAction(MainWindow)
        self.actionLeftView.setObjectName("actionLeftView")
        self.actionIsoView = QtWidgets.QAction(MainWindow)
        self.actionIsoView.setObjectName("actionIsoView")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHotkeys = QtWidgets.QAction(MainWindow)
        self.actionHotkeys.setObjectName("actionHotkeys")
        self.actionToolbarOpen = QtWidgets.QAction(MainWindow)
        self.actionToolbarOpen.setObjectName("actionToolbarOpen")
        self.actionResetView = QtWidgets.QAction(MainWindow)
        self.actionResetView.setObjectName("actionResetView")
        self.actionToolbarCalculate = QtWidgets.QAction(MainWindow)
        self.actionToolbarCalculate.setObjectName("actionToolbarCalculate")
        self.actionToolbarExport = QtWidgets.QAction(MainWindow)
        self.actionToolbarExport.setObjectName("actionToolbarExport")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExportPdf)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionTopView)
        self.menuView.addAction(self.actionBottomView)
        self.menuView.addAction(self.actionFrontView)
        self.menuView.addAction(self.actionBackView)
        self.menuView.addAction(self.actionRightView)
        self.menuView.addAction(self.actionLeftView)
        self.menuView.addAction(self.actionIsoView)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHotkeys)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBarMain.addAction(self.actionToolbarOpen)
        self.toolBarMain.addSeparator()
        self.toolBarMain.addAction(self.actionResetView)
        self.toolBarMain.addSeparator()
        self.toolBarMain.addAction(self.actionToolbarCalculate)
        self.toolBarMain.addSeparator()
        self.toolBarMain.addAction(self.actionToolbarExport)
        self.toolBarMain.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tunnel Concrete Thickness Analyzer"))
        self.groupBoxFileInfo.setTitle(_translate("MainWindow", "File Information"))
        self.labelFile.setText(_translate("MainWindow", "File:"))
        self.lbl_filename.setText(_translate("MainWindow", "File is not loaded yet"))
        self.labelProject.setText(_translate("MainWindow", "Project:"))
        self.lbl_project.setText(_translate("MainWindow", "-"))
        self.labelJob.setText(_translate("MainWindow", "Job:"))
        self.lbl_job.setText(_translate("MainWindow", "-"))
        self.labelTime.setText(_translate("MainWindow", "Time:"))
        self.lbl_time.setText(_translate("MainWindow", "-"))
        self.groupBoxVisualization.setTitle(_translate("MainWindow", "Visualization"))
        self.labelPointSize.setText(_translate("MainWindow", "Point Size:"))
        self.cmb_colormap.setItemText(0, _translate("MainWindow", "jet"))
        self.cmb_colormap.setItemText(1, _translate("MainWindow", "viridis"))
        self.cmb_colormap.setItemText(2, _translate("MainWindow", "plasma"))
        self.cmb_colormap.setItemText(3, _translate("MainWindow", "coolwarm"))
        self.cmb_colormap.setItemText(4, _translate("MainWindow", "rainbow"))
        self.groupBoxSettings.setTitle(_translate("MainWindow", "Analysis Settings"))
        self.labelThicknessField.setText(_translate("MainWindow", "Thickness Field:"))
        self.cmb_dist_field.setItemText(0, _translate("MainWindow", "distances"))
        self.labelMinTarget.setText(_translate("MainWindow", "Min target thickness:"))
        self.spin_target_min.setSuffix(_translate("MainWindow", " mm"))
        self.labelMaxTarget.setText(_translate("MainWindow", "Max target thickness:"))
        self.spin_target_max.setSuffix(_translate("MainWindow", " mm"))
        self.groupBoxResults.setTitle(_translate("MainWindow", "Analysis Results"))
        self.labelArea.setText(_translate("MainWindow", "Surface Area (m²):"))
        self.lbl_area.setText(_translate("MainWindow", "-"))
        self.labelTargetCoverage.setText(_translate("MainWindow", "Target Coverage (m²):"))
        self.lbl_target_coverage.setText(_translate("MainWindow", "-"))
        self.labelVolume.setText(_translate("MainWindow", "Volume (m³):"))
        self.lbl_volume.setText(_translate("MainWindow", "-"))
        self.labelMeanThickness.setText(_translate("MainWindow", "Mean Thickness (mm):"))
        self.lbl_mean_thickness.setText(_translate("MainWindow", "-"))
        self.labelMinThickness.setText(_translate("MainWindow", "Min Thickness (mm):"))
        self.lbl_min_thickness.setText(_translate("MainWindow", "-"))
        self.labelMaxThickness.setText(_translate("MainWindow", "Max Thickness (mm):"))
        self.lbl_max_thickness.setText(_translate("MainWindow", "-"))
        self.labelStdThickness.setText(_translate("MainWindow", "Standard Deviation:"))
        self.lbl_std_thickness.setText(_translate("MainWindow", "-"))
        self.labelNumPoints.setText(_translate("MainWindow", "Number of Points:"))
        self.lbl_num_points.setText(_translate("MainWindow", "-"))
        self.groupBoxDistribution.setTitle(_translate("MainWindow", "Thickness Distribution"))
        self.labelBelow.setText(_translate("MainWindow", "Below Target:"))
        self.lbl_below.setText(_translate("MainWindow", "-"))
        self.labelWithin.setText(_translate("MainWindow", "Within Target:"))
        self.lbl_within.setText(_translate("MainWindow", "-"))
        self.labelAbove.setText(_translate("MainWindow", "Above Target:"))
        self.lbl_above.setText(_translate("MainWindow", "-"))
        self.groupBoxCreateSegment.setTitle(_translate("MainWindow", "Create Segment Tools"))
        self.labelFrom.setText(_translate("MainWindow", "From:"))
        self.labelTo.setText(_translate("MainWindow", "To:"))
        self.btn_select_range.setText(_translate("MainWindow", "📏 Select by Thickness"))
        self.btn_polygon.setToolTip(_translate("MainWindow", "Draw an area to select points"))
        self.btn_polygon.setText(_translate("MainWindow", "🖊 Select Polygon"))
        self.btn_clear_sel.setText(_translate("MainWindow", "❌ Clear Selection"))
        self.lbl_sel_count.setText(_translate("MainWindow", "No selection"))
        self.btn_add_seg.setText(_translate("MainWindow", "✅ Create Segment"))
        self.layer_box.setTitle(_translate("MainWindow", "Layer Manager"))
        self.hint.setText(_translate("MainWindow", "☑ Hide/Show  |  Right-click → Options"))
        self.action_box.setTitle(_translate("MainWindow", "Actions"))
        self.note.setText(_translate("MainWindow", "Calculation and PDF export only use visible layers (☑)."))
        self.btn_calculate.setText(_translate("MainWindow", "📊 Calculate"))
        self.btn_export_pdf.setText(_translate("MainWindow", "📄 PDF Report"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBarMain.setWindowTitle(_translate("MainWindow", "Main"))
        self.actionOpen.setText(_translate("MainWindow", "Open PLY File…"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExportPdf.setText(_translate("MainWindow", "Export PDF Report…"))
        self.actionExportPdf.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionTopView.setText(_translate("MainWindow", "Top View"))
        self.actionTopView.setShortcut(_translate("MainWindow", "T"))
        self.actionBottomView.setText(_translate("MainWindow", "Bottom View"))
        self.actionBottomView.setShortcut(_translate("MainWindow", "G"))
        self.actionFrontView.setText(_translate("MainWindow", "Front View"))
        self.actionFrontView.setShortcut(_translate("MainWindow", "F"))
        self.actionBackView.setText(_translate("MainWindow", "Back View"))
        self.actionBackView.setShortcut(_translate("MainWindow", "B"))
        self.actionRightView.setText(_translate("MainWindow", "Right View"))
        self.actionRightView.setShortcut(_translate("MainWindow", "R"))
        self.actionLeftView.setText(_translate("MainWindow", "Left View"))
        self.actionLeftView.setShortcut(_translate("MainWindow", "L"))
        self.actionIsoView.setText(_translate("MainWindow", "Iso View"))
        self.actionIsoView.setShortcut(_translate("MainWindow", "I"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHotkeys.setText(_translate("MainWindow", "Keyboard Shortcuts"))
        self.actionToolbarOpen.setText(_translate("MainWindow", "Open File"))
        self.actionResetView.setText(_translate("MainWindow", "Reset View"))
        self.actionToolbarCalculate.setText(_translate("MainWindow", "Calculate"))
        self.actionToolbarExport.setText(_translate("MainWindow", "Export PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
