import os
import tempfile
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape
from matplotlib import pyplot as plt
import pdfkit


class HTMLPDFGenerator:

    TEMPLATE_NAME = 'report_template.html'

    def __init__(self, output_path):
        self.output_path = output_path

    def generate(self, ctx):
        html = self._render_template(ctx)

        wkhtmltopdf_path = self._find_wkhtmltopdf()
        config = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf_path)

        with tempfile.NamedTemporaryFile('w', suffix='.html', delete=False, encoding='utf-8') as html_file:
            html_file.write(html)
            html_path = html_file.name

        try:
            options = {
                'enable-local-file-access': None,
                'page-size': 'A4',
                'margin-top': '12mm',
                'margin-bottom': '12mm',
                'margin-left': '12mm',
                'margin-right': '12mm',
            }
            pdfkit.from_file(html_path, self.output_path, options=options, configuration=config)
        except OSError as exc:
            raise RuntimeError(
                'wkhtmltopdf execution failed. Please ensure wkhtmltopdf is installed and available on PATH.'
            ) from exc
        finally:
            try:
                os.unlink(html_path)
            except OSError:
                pass

        return self.output_path

    def _render_template(self, ctx):
        env = Environment(
            loader=FileSystemLoader(Path(__file__).resolve().parents[1] / 'templates'),
            autoescape=select_autoescape(['html', 'xml'])
        )
        template = env.get_template(self.TEMPLATE_NAME)

        project = ctx.get('project_info')
        result = ctx.get('calculation_result')
        dist = ctx.get('thickness_distribution')
        visible_layers = ctx.get('visible_layers', [])
        target_min = ctx.get('target_min')
        target_max = ctx.get('target_max')
        screenshot_path = ctx.get('screenshot_path')

        chart_path = self._create_distribution_chart(dist, target_min, target_max) if dist is not None else None

        return template.render(
            title='Project Report',
            footer='Generated by PPS Report PC',
            project_rows=self._project_rows(project),
            result_main_rows=self._result_main_rows(result),
            result_stats_rows=self._result_stats_rows(result),
            distribution_rows=self._distribution_rows(dist, target_min, target_max),
            chart_path=chart_path and self._escape_path(chart_path),
            segment_notes=self._segment_notes(visible_layers),
            screenshot_path=self._escape_path(screenshot_path) if screenshot_path else None,
        )

    def _project_rows(self, project):
        if project is None:
            return []

        return [
            {'label': 'Project Name', 'value': project.project_name},
            {'label': 'Job Number', 'value': project.job_number},
            {'label': 'Scan Time', 'value': project.formatted_time},
            {'label': 'Source File', 'value': project.original_filename},
        ]

    def _result_main_rows(self, result):
        if result is None:
            return []

        return [
            {'label': 'Surface Area', 'value': f'{result.surface_area_m2:.4f} m²'},
            {'label': 'Volume', 'value': f'{result.volume_m3:.6f} m³'},
        ]

    def _result_stats_rows(self, result):
        if result is None:
            return []

        return [
            {'label': 'Mean Thickness', 'value': f'{result.mean_thickness_mm:.2f} mm'},
            {'label': 'Min Thickness', 'value': f'{result.min_thickness_mm:.2f} mm'},
            {'label': 'Max Thickness', 'value': f'{result.max_thickness_mm:.2f} mm'},
            {'label': 'Std Deviation', 'value': f'{result.std_thickness_mm:.2f} mm'},
            {'label': 'Total Points', 'value': f'{result.num_points:,}'},
        ]

    def _distribution_rows(self, dist, target_min, target_max):
        if dist is None:
            return []

        return [
            {'label': 'Below Target', 'value': f'{dist.below_target:,}'},
            {'label': 'Within Target', 'value': f'{dist.within_target:,}'},
            {'label': 'Above Target', 'value': f'{dist.above_target:,}'},
            {'label': 'Target Range', 'value': f'{target_min} - {target_max} mm'},
        ]

    def _segment_notes(self, visible_layers):
        notes = []
        for layer in visible_layers:
            annotations = getattr(layer, 'annotations', [])
            if not annotations:
                continue

            notes.append({
                'layer_name': layer.name,
                'text': '\n\n'.join(ann['text'] for ann in annotations),
            })
        return notes

    def _create_distribution_chart(self, dist, tmin, tmax):
        if dist is None:
            return None

        fig, ax = plt.subplots(figsize=(8, 4.5))
        labels = [f'< {tmin}', f'{tmin}-{tmax}', f'> {tmax}']
        values = [dist.below_target, dist.within_target, dist.above_target]
        colors = ['#fc8181', '#68d391', '#f6e05e']

        bars = ax.bar(labels, values, color=colors)
        for bar in bars:
            height = bar.get_height()
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                height,
                f'{int(height):,}',
                ha='center',
                va='bottom',
                fontsize=10,
            )

        ax.set_title('Thickness Distribution', fontsize=14, fontweight='bold')
        ax.set_ylabel('Number of Points')
        ax.grid(axis='y', linestyle='--', alpha=0.3)
        plt.tight_layout()

        tmp_dir = tempfile.gettempdir()
        chart_path = os.path.join(tmp_dir, 'pps_report_distribution.png')
        fig.savefig(chart_path, dpi=150)
        plt.close(fig)
        return chart_path

    def _escape_path(self, path):
        if path is None:
            return ''
        return Path(path).resolve().as_uri()

    def _find_wkhtmltopdf(self):
        from shutil import which

        wkhtmltopdf = which('wkhtmltopdf')
        if wkhtmltopdf:
            return wkhtmltopdf

        possible_paths = [
            r"D:\JACON\PPS_Report_PC\data\wkhtmltox\bin\wkhtmltopdf.exe",
            r'C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe',
        ]
        for candidate in possible_paths:
            if os.path.exists(candidate):
                return candidate

        raise RuntimeError(
            'wkhtmltopdf executable not found. Install wkhtmltopdf and ensure it is on the PATH.'
        )
